apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  description: My demo service
  tags:
    - java
    - backend
spec:
  type: service
  lifecycle: production
  owner: group:default/deepthi
  system: default/my-system
  dependsOn:
    - component:default/other-service
  providesApis:
    - default/my-service-api
  consumesApis:
    - default/payment-api
  targets:
    - ./group.yaml
